<?php
$theArray = [1,2,3,4,5];
echo 'count';
echo count($theArray) . '<br>';
echo 'find';
echo in_array(2, $theArray) . '<br>';
$theArray[] = 6;
echo 'add';
print_r($theArray) . '<br>';
array_push($theArray, 7);
echo 'push';
print_r($theArray) . '<br>';
array_unshift($theArray, 0);
echo 'unshift';
print_r($theArray) . '<br>';
array_pop($theArray);
echo 'pop';
print_r($theArray) . '<br>';
array_shift($theArray);
echo 'shift';
print_r($theArray) . '<br>';
unset($theArray[2]);
echo 'unset';
print_r($theArray) . '<br>';
$chunk = array_chunk($theArray, 3);
echo 'chunk';
print_r($chunk) . '<br>';
$theSecondArray = [12, 13, 14, 15, 16];
$merged = array_merge($theArray, $theSecondArray);
echo 'merge';
print_r($merged) . '<br>';
$mergeAgain = [...$theArray, ...$theSecondArray];
echo 'merge again';
print_r($mergeAgain) . '<br>';
$combine = array_combine($theArray, $theSecondArray);
echo 'combine';
print_r($combine) . '<br>';
$keys = array_keys($combine);
echo 'keys';
print_r($keys) . '<br>';
$values = array_values($combine);
echo 'values';
print_r($values) . '<br>';
$flip = array_flip($combine);
echo 'flip';
print_r($flip) . '<br>';
$arrayWithRange = range(0, 10);
echo 'range';
print_r($arrayWithRange) . '<br>';
$map = array_map(function($num){
    return $num * 2;
}, $arrayWithRange);
echo 'map';
print_r($map) . '<br>';
$filter = array_filter($map, fn($num)=> $num <= 10);
echo 'filter';
print_r($filter) . '<br>';
$reduce = array_reduce($map, fn($carry, $num) => $carry + $num);
echo 'reduce';
print_r($reduce) . '<br>';
?>